### ISSUE TITLE
Stopped working 08/04/15

### ISSUE THREAD

**Issue by sometimesnever** [thomasclausen/jquery-facebook-wall#15]
I had just managed to use this great plugin to display my company's facebook feed on the front of our website and then it suddenly stopped working yesterday!

It appears that your demo has also stopped working and I'm wondering what has changed in Facebook's API or ...?

Any help you could give me would be much appreciated.

P.S. Thanks for writing this plugin in the first place!

**Comment by DelightedD0D** [comment]
@sometimesnever  on line 56 of facebook_wall.plugin.js change if (this.is_hidden === undefined) to if (this.is_hidden === false), this will fix the issue

**Comment by thomasclausen** [comment]
@DelightedD0D Thanks for providing a fix...

I've update the plugin, so feel free to grab the latest version.
