### ISSUE TITLE
Fix for issue that caused plugin to stop working on 08/04/15

### ISSUE THREAD

**Issue by DelightedD0D** [thomasclausen/jquery-facebook-wall#16]
on line 56 of facebook_wall.plugin.js change if (this.is_hidden === undefined) to if (this.is_hidden === false)

**Comment by thomasclausen** [comment]
@DelightedD0D Thanks for providing a fix...

**Comment by DelightedD0D** [comment]
Glad to help, thanks for writing the plugin. : )
