### ISSUE TITLE
Date in the local language

### ISSUE THREAD

**Issue by danieleproietti** [thomasclausen/jquery-facebook-wall#17]
Hi,
I installed the plugin on http://andreadigiovanni.it but the date is shown in Norwegian.
Can someone help me? Thanks!

**Comment by thomasclausen** [comment]
Hi @danieleproietti
It's actually in danish, but the two languages have some similarities.

To change the text labels you can add the follwing properties to the options:
```
text_labels: {
	shares: {
		singular: 'Shared % time',
		plural: 'Shared % times'
	},
	likes: {
		singular: '% like',
		plural: '% likes'
	},
	comments: {
		singular: '% comment',
		plural: '% comments'
	},
	like: 'Like',
	comment: 'Comment',
	share: 'Share',
	days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
	months: ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']
}
```

Hope this solves your problem.

**Comment by thomasclausen** [comment]
Just realized this doesn't solve your problem...

I can se that the dates have been hardcoded - I'll try to get it fixed in the next couple of days.

**Comment by danieleproietti** [comment]
Hi @thomasclausen 
like you said, unfortunately, this doesn't solve my problem, but thank you so much for your help, I await the fixed. Thanks, again, for your help, have a nice day.

**Comment by thomasclausen** [comment]
I've now modified the `text_labels` variable to include the labels for dates as well.

```
seconds: {
    few: 'Few seconds ago',
    plural: ' seconds ago'
},
minutes: {
    singular: ' minut ago',
    plural: ' minutes ago'
},
hours: {
    singular: ' hour ago',
    plural: ' hours ago'
},
days: {
    singular: ' day ago',
    plural: ' days ago'
}
```
