### ISSUE TITLE
Image thumbnail size

### ISSUE THREAD

**Issue by mark-chief** [thomasclausen/jquery-facebook-wall#20]
How do I grab a larger image from Facebook? At the moment it’s a tiny 130px x 130px thumbnail. Thanks

**Comment by thomasclausen** [comment]
I'm not sure this plugin even works anymore, because it looks like Facebook have changed there API since I last worked on the plugin.
It looks like you need to get the value from "full_picture" instead.

**Comment by mark-chief** [comment]
Managed to just change `<img src="' + (i + this.object_id) + '/picture?type=album" />` to `<img src="' + (i + this.object_id) + '/picture?type=normal" />` 
Cheers!
